version: '3'
services:

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH

  api:
    build: ../osmi-todo-api/
    ports:
      - 3000:3000
    environment:
      - NEO4J_AUTH
    depends_on:
      - "neo4j"

  frontend:
    build: ../osmi-todo-frontend/
    ports:
      - 80:80
    depends_on:
      - "api"